In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch

from model.integrator import Integrator

In [5]:
# L = np.empty((1,2))
L = np.array(((0,np.pi),(0,np.pi)))

# func = lambda X: torch.sin(X[:,0])*torch.sin(X[:,1])/4
func = lambda X: (torch.sin(X)**2).sum(axis=1)

# N = 64
# x,y = np.meshgrid(np.linspace(0,np.pi,N),np.linspace(0,np.pi,N))
# X = np.concatenate((x.reshape((N**2,1)),y.reshape((N**2,1))),axis=1)
# F = func(X)
# f = F.reshape((N,N))
# fig, axes = plt.subplots(1,1, figsize=(5,5))
# axes.imshow(f,vmin=0,vmax=.25)

igr = Integrator(Nd=2,L=L,Np=1024)

# print(igr.integrate(func,reltol=1e-3,abstol=1e-12,maxiter=1e5))

for n in range(10):
    print(igr.integrate(func,reltol=1e-6,abstol=1e-12,maxiter=1e3).cpu())


tensor([9.8730])
tensor([9.8732])
tensor([9.8664])
tensor([9.8720])
tensor([9.8701])
tensor([9.8664])
tensor([9.8635])
tensor([9.8673])
tensor([9.8658])
tensor([9.8698])
